export const Municipalities = [
  {
    region: 'Atlántida',
    municipalities: [
      'La Ceiba',
      'El Porvenir',
      'Esparta',
      'Jutiapa',
      'La Masica',
      'San Francisco',
      'Tela',
      'Arizona'
    ]
  },
  {
    region: 'Colón',
    municipalities: [
      'Trujillo',
      'Balfate',
      'Iriona',
      'Limon',
      'Saba',
      'Santa Fe',
      'Santa Rosa de Aguan',
      'Sonaguera',
      'Tocoa',
      'Bonito Oriental'
    ]
  },
  {
    region: 'Comayagua',
    municipalities: [
      'Comayagua',
      'Ajuterique',
      'El Rosario',
      'Esquias',
      'Humuya',
      'La Libertad',
      'Lamani',
      'La Trinidad',
      'Lejamani',
      'Meambar',
      'Minas de Oro',
      'Ojos de Agua',
      'San Jerónimo',
      'San Jose de ',
      'San Jose del Potrero',
      'San Luis',
      'San Sebastian',
      'Siguatepeque',
      'Villa de San Antonio',
      'Las Lajas',
      'Taulabe'
    ]
  },
  {
    region: 'Copán',
    municipalities: [
      'Santa Rosa de Copan',
      'Cabana',
      'Concepción',
      'Copan Ruinas',
      'Corquin',
      'Cucuyagua',
      'Dolores',
      'Dulce Nombre',
      'El Paraiso',
      'Florida',
      'La Jigua',
      'La Union',
      'Nueva Arcadia',
      'San Agustin',
      'San Antonio',
      'San Jeronimo',
      'San Jose',
      'San Juan de Opoa',
      'San Nicolas',
      'San Pedro',
      'Santa Rita',
      'Trinidad de Copan',
      'Veracruz'
    ]
  },
  {
    region: 'Cortés',
    municipalities: [
      'San Pedro Sula',
      'Choloma',
      'Omoa',
      'Pimienta',
      'Potrerillos',
      'Puerto Cortes',
      'San Antonio de Cortes',
      'San Francisco de Yojoa',
      'San Manuel',
      'Santa Cruz de Yojoa',
      'Villanueva',
      'La Lima'
    ]
  },
  {
    region: 'Choluteca',
    municipalities: [
      'Choluteca',
      'Apacilagua',
      'Concepcion de Maria',
      'Duyure',
      'El Corpus',
      'El Triunfo',
      'Marcovia',
      'Morolica',
      'Namasigue',
      'Orocuina',
      'Pespire',
      'San Antonio de Flores',
      'San Isidro',
      'San Jose',
      'San Marcos de Colon',
      'Santa Ana de Yusguare'
    ]
  },
  {
    region: 'El Paraíso',
    municipalities: [
      'Yuscaran',
      'Alauca',
      'Danli',
      'El Paraiso',
      'Guinope',
      'Jacaleapa',
      'Liure',
      'Moroceli',
      'Oropoli',
      'Potrerillos',
      'San Antonio de Flores',
      'San Lucas',
      'San Matias',
      'Soledad',
      'Teupasenti',
      'Texiguat',
      'Vado Ancho',
      'Yauyupe',
      'Trojes'
    ]
  },
  {
    region: 'Francisco Morazan',
    municipalities: [
      'Distrito Central',
      'Alubaren',
      'Cedros',
      'Curaren',
      'El Porvenir',
      'Guaimaca',
      'La Libertad',
      'La Venta',
      'Lepaterique',
      'Maraita',
      'Marale',
      'Nueva Armenia',
      'Ojojona',
      'Orica',
      'Reitoca',
      'Sabanagrande',
      'San Antonio de Oriente',
      'San Buenaventura',
      'San Ignacio',
      'San Juan de Flores',
      'San Miguelito',
      'Santa Ana',
      'Santa Lucia',
      'Talanga',
      'Tatumbla',
      'Valle de Angeles',
      'Villa de San Francisco',
      'Vallecillo'
    ]
  },
  {
    region: 'Gracias a Dios',
    municipalities: [
      'Puerto Lempira',
      'Brus Laguna',
      'Ahuas',
      'Juan Francisco  Bulnes',
      'Ramón Villeda Morales',
      'Wampusirpi'
    ]
  },
  {
    region: 'Intibucá',
    municipalities: [
      'La Esperanza',
      'Camasca',
      'Colomoncagua',
      'Concepcion',
      'Dolores',
      'Intibuca',
      'Jesus de Otoro',
      'Magdalena',
      'Masaguara',
      'San Antonio',
      'San Isidro',
      'San Juan',
      'San Marcos de Sierra',
      'San Miguelito',
      'Santa Lucia',
      'Yamaranguila',
      'San Francisco de Opalaca'
    ]
  },
  {
    region: 'Islas de la Bahía',
    municipalities: [
      'Roatan',
      'Guanaja',
      'Jose Santos Guardiola',
      'Utila'
    ]
  },
  {
    region: 'La Paz',
    municipalities: [
      'La Paz',
      'Aguanqueterique',
      'Cabanas',
      'Cane',
      'Chinacla',
      'Guajiquiro',
      'Lauterique',
      'Marcala',
      'Mercedes de Oriente',
      'Opatoro',
      'San Antonio del Norte',
      'San Jose',
      'San Juan',
      'San Pedro de Tutule',
      'Santa Ana',
      'Santa Elena',
      'Santa Maria',
      'Santiago de Puringla',
      'Yarula'
    ]
  },
  {
    region: 'Lempira',
    municipalities: [
      'Gracias',
      'Belen',
      'Candelaria',
      'Cololaca',
      'Erandique',
      'Gualcince',
      'Guarita',
      'La Campa',
      'La Iguala',
      'Las Flores',
      'La Union',
      'La Virtud',
      'Lepaera',
      'Mapulaca',
      'Piraera',
      'San Andres',
      'San Francisco',
      'San Juan Guarita',
      'San Manuel Colohete',
      'San Rafael',
      'San Sebastian',
      'Santa Cruz',
      'Talgua',
      'Tambla',
      'Tomala',
      'Valladolid',
      'Virginia',
      'San Marcos de Caiquin'
    ]
  },
  {
    region: 'Ocotepeque',
    municipalities: [
      'Ocotepeque',
      'Belen Gualcho',
      'Concepcion',
      'Dolores Merendon',
      'Fraternidad',
      'La Encarnacion',
      'La Labor',
      'Lucerna',
      'Mercedes',
      'San Fernando',
      'San Francisco del Valle',
      'San Jorge',
      'San Marcos',
      'Santa Fe',
      'Sensenti',
      'Sinuapa'
    ]
  },
  {
    region: 'Olancho',
    municipalities: [
      'Juticalpa',
      'Campamento',
      'Catacamas',
      'Concordia',
      'Dulce Nombre de Culmi',
      'El Rosario',
      'Esquipulas del Norte',
      'Gualaco',
      'Guarizama',
      'Guata',
      'Guayape',
      'Jano',
      'La Union',
      'Mangulile',
      'Manto',
      'Salama',
      'San Esteban',
      'San Francisco de Becerra',
      'San Francisco de La Paz',
      'Santa Maria del Real',
      'Silca',
      'Yocon',
      'Patuca'
    ]
  },
  {
    region: 'Santa Bárbara',
    municipalities: [
      'Santa Barbara',
      'Arada',
      'Atima',
      'Azacualpa',
      'Ceguaca',
      'Concepcion del Norte',
      'Concepcion del Sur',
      'Chinda',
      'El Nispero',
      'Gualala',
      'Ilama',
      'Macuelizo',
      'Naranjito',
      'Nuevo Celilac',
      'Petoa',
      'Proteccion',
      'Quimistan',
      'San Francisco de Ojuera',
      'San Jose de Colinas',
      'San Luis',
      'San Marcos',
      'San Nicolas',
      'San Pedro Zacapa',
      'San Vicente Centenario',
      'Santa Rita',
      'Trinidad',
      'Las Vegas',
      'Nueva Frontera'
    ]
  },
  {
    region: 'Valle',
    municipalities: [
      'Nacaome',
      'Alianza',
      'Amapala',
      'Aramecina',
      'Caridad',
      'Goascoran',
      'Langue',
      'San Francisco de Coray',
      'San Lorenzo'
    ]
  },
  {
    region: 'Yoro',
    municipalities: [
      'Yoro',
      'Arenal',
      'El Negrito',
      'El Progreso',
      'Jocon',
      'Morazan',
      'Olanchito',
      'Santa Rita',
      'Sulaco',
      'Victoria',
      'Yorito'
    ]
  }
]